Feature/450 online task background
ConservationInternational/cplus-plugin pull request #475
Opened 2024-06-10 11:40 UTC by zamuzakki

This is PR for running online task in background.
Demo: https://youtu.be/Z-31nvtCkKU

2024-08-05 04:22 UTC, zamuzakki commented
Demo for showing online task status when plugin opens: https://youtu.be/3U8E5Rj1gWg

2024-08-19 13:09 UTC, danangmassandy requested changes

2024-08-19 13:09 UTC, danangmassandy commented on src/cplus_plugin/api/scenario_task_output_download.py
> +class ScenarioTaskOutputDownload(ScenarioAnalysisTaskApiClient):
@zamuzakki can you add doc strings to the class and public methods? there are several changes, I added a comment here but please add to other places.

2024-08-27 13:28 UTC, zamuzakki commented
Replaced in favor of https://github.com/ConservationInternational/cplus-plugin/pull/513

2024-08-28 01:19 UTC, closed without merging