Feature/451 plugin qgs network
ConservationInternational/cplus-plugin pull request #517
Opened 2024-09-02 07:22 UTC by zamuzakki

This is PR for https://github.com/ConservationInternational/cplus-plugin/issues/451 and split PR from https://github.com/ConservationInternational/cplus-plugin/pull/468.

It removes requests from plugin and uses QgsNetworkAccessManager to send request and `qgis:filedownloader` to download file.

2024-09-03 02:39 UTC, danangmassandy requested changes

2024-09-03 02:39 UTC, danangmassandy commented on src/cplus_plugin/api/request.py
> +    def submit_scenario_detail(self, scenario_detail: dict) -> bool:
This is incorrect return type if the function returning string of scenario detail UUID

2024-09-03 02:39 UTC, danangmassandy commented on src/cplus_plugin/api/request.py
> +            if isinstance(reply, QNetworkReply) or isinstance(reply, MagicMock):
@zamuzakki is the MagicMock from test? which test is it? I think we can also mock the whole function _read_json_response.

2024-09-05 08:31 UTC, Samweli approved these changes

2024-09-05 08:31 UTC, merged